#!/usr/bin/env python3
import os
import sys

parent_dir = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir))
if os.path.exists(os.path.join(parent_dir, "components")):
    sys.path.append(parent_dir)

from components.main.stahlta import stahlta_asyncio_run

if __name__ == "__main__":
    stahlta_asyncio_run()
